#' Remove empty accession numbers and other problematic rows
#' @param hits_table a data.frame generated by parse_primer_hits
#'        or by iterative_primer_search
#' @return a data.table with problematic rows removed
#' @export
filter_primer_hits <- function(hits_table) {
    # filter like get_blast_seeds used to
}